- hosts: localhost
  tasks:
  - name: Add GPG key for the offical Docker repository
    apt_key:
      url: "https://download.docker.com/linux/ubuntu/gpg"
      state: present

  - name: Add Docker Repo
    apt_repository:
      repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable"
      state: present

  - name: Install Docker
    apt: package=docker-ce state=installed

  - name: Start/Restart service docker-ce
    service: name=docker state=started enabled=yes
